version: '3'
services:
  ####################################
  # HelloWorldPublish service + Dapr sidecar
  ####################################
  helloworldpublish:
    build: ./API.HelloWorld.Publish
    depends_on:
      - rabbitmq
      - placement
    networks:
      - hello-dapr
    ports:
      - "40100:80"
      - "50001:50001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
  helloworldpublish-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
              "-app-id", "helloworldpublish",
              "-app-port", "80",
              "-placement-host-address", "placement:50006",
              "-components-path", "/components"]
    volumes:
      - "./API.Components/:/components"
    depends_on:
      - helloworldpublish
      - rabbitmq
    network_mode: "service:helloworldpublish"

  ####################################
  # HelloWorldSubscribe service + Dapr sidecar
  ####################################
  helloworldsubscribe:
    build: ./API.HelloWorld.Subscriber
    depends_on:
      - rabbitmq
      - placement
    networks:
      - hello-dapr
    ports:
      - "40200:80"
      - "50002:50001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
  helloworldsubscribe-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
              "-app-id", "helloworldsubscribe",
              "-app-port", "80",
              "-placement-host-address", "placement:50006",
              "-components-path", "/components"]
    volumes:
      - "./API.Components/:/components"
    depends_on:
      - helloworldsubscribe
      - rabbitmq
    network_mode: "service:helloworldsubscribe"

  ############################
  # RabbitMQ service
  ############################
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    networks:
      - hello-dapr

  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - hello-dapr

networks:
  hello-dapr: